#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

pnpm dlx start-server-and-test --expect 404 \
  "pnpm dlx @stoplight/prism-cli mock -d --json-schema-faker-fillProperties=false test/fixtures/ai_guard.openapi.json" \
  4010 \
  "bundler exec rake test"
